### ISSUE TITLE
Default Image changed

### ISSUE THREAD

**Issue by dhechler** [WebDevStudios/StartBox#12]
I have a default post image set in the theme options. I then uploaded an image to the media library and did not attach the image to any post or page. 

The newly uploaded image is now set as the "default post image", but not in the theme options. The theme option shows the correct default image, but the theme is not using that one.

**Comment by brichards** [comment]
I just published branch 2.6.1 that _should_ fix this issue. Want to download that and give it a try? The root problem is that we were simply not passing the $post_id through to the thumbnail function. Have a look: https://github.com/brichards/StartBox/tree/2.6.1

**Comment by dhechler** [comment]
That seems to work. Awesome!
