### ISSUE TITLE
Can't use custom sidebars to override Primary and Secondary at the same time

### ISSUE THREAD

**Issue by Pypeline** [WebDevStudios/StartBox#14]
To reproduce:
-Use a layout allowing both Primary and Secondary sidebars to show.
-Add widgets to both Primary and Secondary sidebars.
-Create two custom sidebars, one to replace primary and one to replace secondary.
-Secondary is not replaced.

I think it may be in the check for which sidebars to output about line 285 of sidebars.php.

**Comment by brichards** [comment]
Fixed in the 2.7 branch via commit 6d7f9847e4a2b8c4cac9490d8903b0042da14b42
