### ISSUE TITLE
3 Pain Points that should be addressed with Responsive/Adaptive styles

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/StartBox#26]
I feel very strongly about 3 issues: 1) The font should not be increased to children's book sizes, 2) the comment nesting needs to be handled more eloquently than indentation, and 3) there should be a solution for videoes so they don't break the layout

**Comment by brichards** [comment]
I agree on all 3 points. Since we decided that SB (at least in its current form) would not have a built-in responsive stylesheet I'm going to close this issue. It is probably very relevant for the 3.0 build discussion, though.
