### ISSUE TITLE
Rename license.txt and readme.txt to LICENSE.txt and README.txt

### ISSUE THREAD

**Issue by brichards** [WebDevStudios/StartBox#27]
These files are traditionally uppercase so they move to the top in alphabetical reodering of files. (h/t @GaryJones)

**Comment by jtsternberg** [comment]
https://github.com/WebDevStudios/StartBox/blob/master/license.txt - seems to include stuff at the bottom 20% that isn't part of the license. (h/t @GaryJones)

**Comment by williamsba** [comment]
It matches the full license: http://www.gnu.org/licenses/gpl-2.0.txt
