### ISSUE TITLE
Use ARIA roles, states and properties

### ISSUE THREAD

**Issue by GaryJones** [WebDevStudios/StartBox#29]
Use [WAI-ARIA](http://www.w3.org/TR/wai-aria/) roles, states and properties within any markup that SB provides that may be used in child themes to make those bits more accessible to assistive user agents

One example would be to apply [landmark roles](http://www.w3.org/TR/wai-aria/roles#landmark_roles) to main or sidebar sections of content, search or general forms, navigation, header etc. to allow recognition of those landmarks and provide easy navigation between those sections.

[States and Properties](http://www.w3.org/TR/wai-aria/states_and_properties) may be applied later on.

**Comment by brichards** [comment]
Related (with excellent 1min video explanation): http://www.paciellogroup.com/blog/2013/02/using-wai-aria-landmarks-2013/
