### ISSUE TITLE
Lost sidebars

### ISSUE THREAD

**Issue by banunki** [WebDevStudios/StartBox#45]
I just upgraded to version 2.7.1 and I lost the primary sidebar for every page. Everything was working fine with the 2.7 upgrade.

**Comment by brichards** [comment]
Sorry for the trouble, I know how annoying that is! Last night I pushed up a 2.7.2 branch that should fix this problem, would you be willing to test that for me and confirm? https://github.com/WebDevStudios/StartBox/tree/2.7.2

**Comment by banunki** [comment]
Hey Brian,

I just installed the update and the whole site went down. I'm checking with
my host right now if it's anything on there end. The site is
www.happymittengames.com. I didn't want to put it on the forum because we
haven't officially launched yet.

-jeff

**Comment by brichards** [comment]
Yikes! Hopefully it's unrelated, there was nothing significant enough in the 2.7.2 changeset that could bring about collapsing your site.

But, if you still have SFTP access, it's not entirely impossible I suppose. Double check to make sure that the the theme directory you created is /wp-content/themes/startbox/, and not something like /wp-content/themes/StartBox-2.7.2/. Let me know where you end up!

**Comment by banunki** [comment]
Hey Brian,

That's what happened- it renamed the folder. I went in and changed it;
everything looks good at the moment. I'll be working on it tonight and can
let you know if anything comes up.

Another question- I love Startbox and was wondering if you have any sort of
affiliate program? I'm currently in the process of launching a board game
publishing company and a website/ podcast resource for teachers. To
complement that, I'm going to turn my personal site as a blog telling my
entrepreneurial journey. I plan on having a resource page of all the things
I'm using and would love to promote your work. Let me know what you think.

Thanks again for the quick reply and awesome work!

-Jeff

On Apr 4, 2013, at 10:42 AM, Brian Richards notifications@github.com
wrote:

Yikes! Hopefully it's unrelated, there was nothing significant enough in
the 2.7.2 changeset that could bring about collapsing your site.

But, if you still have SFTP access, it's not entirely impossible I suppose.
Double check to make sure that the the theme directory you created is
/wp-content/themes/startbox/, and not something like
/wp-content/themes/StartBox-2.7.2/. Let me know where you end up!

—
Reply to this email directly or view it on
GitHubhttps://github.com/WebDevStudios/StartBox/issues/45#issuecomment-15901300
.
