### ISSUE TITLE
Remove colorbox as a dependency for startbox.js

### ISSUE THREAD

**Issue by jtsternberg** [WebDevStudios/StartBox#49]
Right now, several JS files are being loaded as dependencies for startbox.js.
The one that stands out to me as needing to be optional is colorbox. Not all installations will need colorbox.

**Comment by brichards** [comment]
I concur. startbox.js currently has 3 colorbox rules that therefore make it a requirement. If you can either make them conditionally applicable, or move them someplace more logical, we can drop the hard requirement for colorbox.
