### ISSUE TITLE
Custom sidebars don't check for sidebar post type before applying default slug, and also could end up with the same default slug on multiple posts.

### ISSUE THREAD

**Issue by Pypeline** [WebDevStudios/StartBox#57]
I was going to put in a pull request for it but my current one is still open. This checks for the sidebar post type (I've had other CPT of mine end up with 'custom-sidebar' as their slug) and also adds the ID onto the end of the "custom-sidebar" default slug.

at line 70 in /includes/extensions/sidebars.php

`// Make sure this isn't an unsaved post (auto-draft) and is a custon sidebar post
    if ( 'auto-draft' != $postarr['post_status'] && 'sidebar' == $data['post_type'] && '' == $data['post_name'] ) {
        $data['post_name'] = 'custom-sidebar-'.$postarr['ID'];
    }`

**Comment by Pypeline** [comment]
let me just add this example so you can see how bad it can get. check out this RSS feed and do a Find for "custom-sidebar"   http://blogs.kidshopeusa.org/?feed=rss

Poor blog has all kinds of permalinks with "custom-sidebar" in it. Please address soon.

**Comment by jtsternberg** [comment]
This issue has been addressed in the 2.7.2 branch (f1e5e68f91b288135ce714ca734439e1e377e032) and should be merged to trunk in the next week. cc: @brichards

**Comment by Pypeline** [comment]
Ah, true that, thanks for pointing it out. It does not address the issue of creating multiple sidebars with the same slug of "custom-sidebar" though as my snippet above does.

**Comment by brichards** [comment]
Thanks for the heads up @Pypeline!
