### ISSUE TITLE
Fatal error: Call to undefined function sb_supported_layouts()

### ISSUE THREAD

**Issue by goldrazor** [WebDevStudios/StartBox#77]
Hello,

My order : #11678

My website : http://www.satine-relooking.com

There is a bug on modbloger version.

I have installed wordpress 3.8.1 and startbox 2.7.2

Then, i have installed modblog 1.2 and when i upload functions.php file of modblog, i have this error message : 

Fatal error: Call to undefined function sb_supported_layouts() in /homez.726/babyshow/relooking/wp-content/themes/startbox/includes/admin/layout.php on line 18

So i check on layout.php on line 18 and on line 26 and on line 34 there is : 

'options'   =>  sb_supported_layouts('sb-layouts-home'),

Whats happned whith this function ?

And when i delete this function, i have this error : 

Fatal error: Cannot redeclare sb_admin_init() (previously declared in /homez.726/babyshow/relooking/wp-content/themes/startbox/includes/admin/admin.php:10) in /homez.726/babyshow/relooking/wp-content/themes/startbox/includes/admin/admin.php on line 22

Could you send me all sames files of http://modern.demo.wpstartbox.com/ ? goldrazor on gmail.com

Best regards,
Kevin

**Comment by brichards** [comment]
The issue here is that StartBox hadn't fully uploaded to the server. I helped Kevin resolve the issue via email.

**Comment by goldrazor** [comment]
Thx my friend, very nice job. You are serious and pro.

How do you do to resolve problem ?

Best regards
Kevin
